services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=your_secret_key_here
      - DATABASE_NAME=warehouse_db
      - DATABASE_USER=Yan
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: Yan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warehouse_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
